<?php
class C_Front extends MY_Controller {
	var $data;
	public $forwardemail;
	public $nicename;
	public function __construct() 
	{
		parent::__construct();
        $this->load->model("UsersModel",'users');
        $this->load->model("CompanyModel",'c');
	    $this->data=array();
		$this->forwardemail=$this->config->item('email_server');
		$this->nicename=$this->config->item('email_nicename');		
	}

	public function index() {
		if(!$this -> session -> userdata('logged_in'))
		{
		    $this->access_site();
		}
		else
		{
		 $this->vehicles();
		}
	}//End of index file
	
	//function to load the login view if session is timed-out
	public function access_site(){
		$data['form'] = '';
		$data['page']='Login';
		$data['title']='Welcome';
		$this -> load -> view('index', $data);
	}
	public function chooseVehicle(){
		$data['form'] = '';
		$data['page']='Login';
		$data['title']='Vehicle Selector';
		$this -> load -> view('vehicleSelector', $data);
	}
	public function vehicles() 
	{
		if(!$this -> session -> userdata('logged_in'))
		{
		    $this->access_site();
		}
		else{
		$data['status']="";
		$data['response']="";
		$data['form'] = '<p class="error"><br/><br/>No form has been chosen<br/><br/><p>';
		$data['form_id']='';
		$this->load_template_view();
		
		}
	}


	public function formviewer() {
		$data['form'] = '<p class="error"><br/><br/>Choose a Form from the left panel to get started<br/><br/><p>';
		$this -> load -> view('form_empty', $data);
	}

public function manageUsers()
{
   //$data['form'] = 'oil/fortifiedOil_B1';
   //$data['form_id'] = 'fortifiedOil_B1';
    $data['h_title']="Manage Users";
	$data['content_page'] = 'manage_users';	
    $this -> load -> view('template_loggedin', $data);
	
   //$this -> load -> view('dashboard/manage_users', $data);   	
}

public function activate($code)
	{
	//	echo $code;
	  $filter=array('activationcode' => $code);
	  $res=$this->users->get_details($filter);
	//  print_r($res);
	//  die();
   	  $count=count($res);		
		if($count>0)
		{
		  $url = base_url();
		  foreach($res as $row):
		  $email=$row->userEmail;
		  $uid=$row->usersID;
		  $name=$row->usersFullnames;	
		  endforeach;	  

          $message="Dear $name,\r\nYour account has been activated. Proceed to login: $url .\r\n\r\nThis email was atomaticaly generated by the system";

          $this->email->set_newline("\r\n");  
          $this->email->from($this->forwardemail, $this->nicename);
          $this->email->subject('Account activation notification');
          $this->email->message($message);
          $this->email->to($email);
     if (! $this->email->send())
      {
		$data = array('act_msg'=> "Could not activate your account. The email server is not responding. Please try again later or contact admin.");	
	    $this->session->set_userdata($data);
        redirect('manageUsers');
      }
		else
		{

		$udata=array('activationcode'=>'y','is_active'=>1);
		$this->users->activate($uid,$udata);
		$data = array('act_msg'=> "Your account has been successfully activated!! Please login to your account");	        $this->session->set_userdata($data);
        redirect('manageUsers');

		}

		}

		else

		{		

			$data = array('act_msg'=> "Account not activated. The activation code provided is not/ no longer valid for such a purpose.");	
			$this->session->set_userdata($data);
            redirect('manageUsers');

		}

	}
}
?>