<?php
/*helps authenticate a user*/
//error_reporting(0);
class Company extends MY_Controller {

	public $c_companyTypes;
	public $forwardemail;
	public $nicename;

    public function __construct() {
        parent::__construct();
        $this->load->model("CompanyModel",'c');
		$this->load->model("BrandModel",'b');
        $this->load->model("CompanyType",'company_type');
        $this->load->model("Foodtypes",'foodtypes');
        $this->load->model("UsersModel",'users');
		$this->forwardemail=$this->config->item('email_server');
		$this->nicename=$this->config->item('email_nicename');
		$this->is_logedIn();
    }


    public  function index($filter=""){
       $result= $this->c->get_details();
    }
	public function add($id="")
	{
		if(isset($_POST))
		{	$emailAddress=$this->input->get_post('email',TRUE);
		
			$filter=array('userName' => $emailAddress,'userEmail'=>$emailAddress);
			if(count($this->users->get_details($filter))>0){
				$data = array('reg_msg'=> "The users email already exist, please try another one");	
				$this->session->set_userdata($data);
				redirect('manageCompanies');
				exit;
			}
			$contact_person=$this->input->get_post('c_person',TRUE);
           
			
			$cmpny=$this->input->get_post('inputCName',TRUE);
            $company_code=$this->input->get_post('inputCcode',TRUE);
           
		    $ctype=$this->input->get_post('inputCType',TRUE);
			$foodtype=$this->input->get_post('inputFType',TRUE);
			
			$nms=$this->company_type->get_companyName($ctype);
			foreach($nms as $row)
			{
				$ctype_name=$row->company_type_name;
			}
			if($foodtype=="0")
			{
				$c_foodtype="MOPHS";
			}
			else
			{
				$itms = explode ("(",$foodtype);
				$str=$itms[1];
				$str= str_replace(")","",$str);				
				$c_foodtype=$str;
			}	
						
			$phone=$this->input->get_post('phone',TRUE);
			//.date('Y').
			$uname=$ctype."ADM".gencode(4);
			$pass=genBigcode(8);
			
			/*$filter=array('userName' => $emailAddress);
   	  		$available_users=count($this->users->get_details($filter));
			
	  		while($available_users>0)
	  		{
	    		$uname=$ctype."ADM".gencode(4);
				$filter=array('userName' => $uname);
   	    		$cde=count($this->users->get_details($filter));
	  		}*/
			
				
		if(empty($id))
		{	
			$code=genBigcode(6);
	  		$filter=array('activationcode' => $code);
   	  		$cde=count($this->users->get_details($filter));
	  		while($cde>0)
	  		{
	    		$code=genBigcode(6);
				$filter=array('activationcode' => $code);
   	    		$cde=count($this->users->get_details($filter));
	  		}
   	  	$url = site_url()."activate/$code";
		
      	$message="Dear $contact_person,\r\nYou have been created as the administrator for $cmpny.......\r\n\r\nCompany details::\r\n Company Name: $cmpny\r\n  Company Code: $company_code\r\n Company Type: $ctype_name\r\n Vehicle Type: $c_foodtype\r\n\r\nYour Login credentials ::\r\n Username: $uname\r\n  Password: $pass\r\nPlease click on the link bellow to activate your accoutnt:$url.\r\n\r\nThis email was atomaticaly generated by the system";

	     $this->email->set_newline("\r\n");  
         $this->email->from($this->forwardemail,$this->nicename);
         $this->email->subject('Account registration request');
         $this->email->message($message);
         $this->email->to($emailAddress);
     if (!$this->email->send())
      { 
		$data = array('reg_msg'=> "Could not create company account. The email server is not responding. Please try again later or contact admin.");	
	    $this->session->set_userdata($data);
		// echo "server error";
		// die();
        redirect('manageCompanies');
      }
	  else
	  {
		 
		 $resp=$this->c->add_company($c_foodtype);
			if($resp==TRUE)
			{
				 $filter=array('company_name' => $cmpny,'company_code' => $company_code);				
				 $rsp=$this->c->get_details($filter);
				 foreach($rsp as $rw):
				 $c_id=$rw->company_id;
				 $affiliation=$rw->affiliation;
				 endforeach;
				 $details = array(
                'usersFullnames'=>$contact_person,
                'userName'=>$emailAddress,
                'userEmail' =>$emailAddress,
                'company_id' => $c_id,
				'userPassword'=>md5($pass),
				'userRights'=>1,
				'user_role'=>1,
				'activationcode'=>$code,
				'is_active'=>0,
				'affiliation'=> $affiliation,
            	);
				//add_company
				$data = array('reg_msg'=> "Company and default user created. Login credentials sent to $emailAddress.");
				$this->users->add_user($details);
	     		$this->session->set_userdata($data);
		 		redirect('manageCompanies');
			}
	  	  }	
        }	
		else
		{			
			$resp=$this->c->update_dets($c_foodtype,$id);
			if($resp==TRUE)
			{
				redirect('manageCompanies');
			}
		}
		
		}
    }
 function change_dets($id)
{
     $names=trim($this->input->get_post('c_person',TRUE));
   	 $userEmail=trim($this->input->get_post('email',TRUE));
   	 $phone=trim($this->input->get_post('phone',TRUE));
	 $pass=genBigcode(8);
	//die();
	 	$filter=array('company_id' => $id);
	 	$dets=$this->c->get_details($filter);	
	 	foreach($dets as $row)
	 	{
			$old_email=trim($row->emailAddress);
	 	}
		if($old_email===trim($userEmail))
			{
				$this->c->update_cperson($id);
	    		redirect('manageCompanies');
			}
		else
			{
			$filter=array('userEmail' => $old_email,'company_id' =>$id);
			$dets=$this->users->get_details($filter);	
			//print_r($dets);
			foreach($dets as $row)
			{
				 	$names=trim($row->usersFullnames);
				 	$uname=trim($row->userName);
					$uid=trim($row->usersID);
			}	
		//	die();		
  	  			$url = base_url();
      			$message="Dear $names,\r\nYou changed your email address....... Your Login credentials are:\r\n Username: $uname\r\n  Password: $pass\r\nPlease click on the link bellow to access your accoutnt:$url.\r\n\r\nThis email was atomaticaly generated by the system";

	     		$this->email->set_newline("\r\n");  
         		$this->email->from($this->forwardemail,$this->nicename);
         		$this->email->subject('Changed login credentials.');
         		$this->email->message($message);
         		$this->email->to($userEmail);
     			if (!$this->email->send())
      				{ 
						$data = array('updt_msg'=> "Could not update user account details. The email server is not responding. Please try again later or contact admin.");	
	    				$this->session->set_userdata($data);
       					redirect('manageCompanies');
      				}
	  			else
	  				{
		 				$this->c->update_cperson($id);
						$details = array('userEmail' =>$userEmail,'userPassword'=>$pass);
						print_r($details);
						$data = array('updt_msg'=> "Company default user details updated. Login credentials sent to $userEmail.");
						$this->users->activate($uid,$details);
						$this->session->set_userdata($data);
	     				redirect('manageCompanies');
	  			    }
			
	  	}
	
}
    public function update()
	{
     $this->c->update();   
    }
	public function update_dets($id)
	{
		 $resp=$this->c->update_dets($id);  
		 if($resp==TRUE)
			{
				redirect('openComany/'.$id);
			}
	}
	
	public function add_form($id="") 
	{
		$data['item_id']=$id;
		if(!empty($id))
		{
			$result= $this->c->get_details(array('company_id'=>$id));
			$data['result']=$result;			
		}
	    $data['comptypes']=$this->company_type->get_details();
		$data['foodtype']=$this->company_type->get_Typedetails();
		$this -> load -> view('dashboard/companies/add_companies', $data);
	}
	public function edit_cperson($id) 
	{
		$data['item_id']=$id;
		$result= $this->c->get_details(array('company_id'=>$id));
		$data['result']=$result;
		$this -> load -> view('dashboard/companies/edit_cperson', $data);
	}
	public function edit_user($id="") 
	{
		$data['item_id']=$id;
		if(!empty($id))
		{
			$result= $this->c->get_details(array('company_id'=>$id));
			$data['result']=$result;			
		}
	    $data['comptypes']=$this->company_type->get_details();
		$data['foodtype']=$this->company_type->get_Typedetails();
		$this -> load -> view('dashboard/companies/edit_cmpany', $data);
	}
	
	private function getCompanyTypes() 
	{
		return $this -> c_companyTypes=$this->company_type->get_details();
	}	
		
	public function manageCompanies()
	{
		$cat = $this -> session -> userdata('vehicle');
		 $data['h_title']="Registered companies";
		 $data['mh_title']="COMPANIES";
		 
		 $data['content_page'] = 'companies/manage_companies';
		 $tmpl = array ( 'table_open'  => '<table id="big_table" border="0" cellpadding="0" cellspacing="0" class="mytable" style="font-size:12px; width:100%">' );
		 $this->table->set_template($tmpl);         
		 $this->table->set_heading('Company Name','Company Code','Company Type','Food Type','Contact Person','Email','Actions'); 
		$this -> load -> view('template_loggedin', $data);  	
	}

	function getList()
		{
			$this->datatables->select('company_id,company_name,company_code,company_type_id,foodtype,contact_person,emailAddress')
			->unset_column('company_id')
			->add_column('Actions', get_buttons('$1'),'company_id')
			->where('company_name != "MOPHS"')
			->from('company');        
			echo $this->datatables->generate();
		}
	public  function openComany($id="user")
		{
			if($id=="user")
			{
			 $id= $this ->session -> userdata('companyID');
			}
		   $filter=array('company_id'=>$id);
		   $result= $this->c->get_details($filter);
		   foreach($result as $row):
		   $c_name=ucfirst(trim($row->company_name));
		   endforeach;
		   $data['h_title']="Profile & settings";
		   $data['mh_title']=strtoupper($c_name);
		   $data['content_page'] = 'companies/companyPage';
		   $data['result']=$result;
		   $data['company_id']=$id;
		   $data['content']="Vehicles";
		   $tmpl = array ( 'table_open'  => '<table id="big_table" border="0" cellpadding="0" cellspacing="0" class="mytable" style="font-size:12px; width:100%">' );
		 $this->table->set_template($tmpl);         
		 $this->table->set_heading('Brand Name','Actions'); 
		   $this -> load -> view('template_loggedin', $data); 
		}

	function getBrands($id)
		{
		
			$this->datatables->select('brand_id,brand_name','company_name') 
			->unset_column('brand_id')
			->add_column('Actions', get_brandbuttons('$1'),'brand_id') 
			->where('company.company_id', $id)
			->join('company','company.company_id = companybrands.company_id')
			->from('companybrands');
			
			echo $this->datatables->generate();
		}	
		
	public function addProduct($id="") 
	{
	   $filter=array('company_id'=>$this ->session -> userdata('companyID'));
       $result= $this->c->get_details($filter);
	   foreach($result as $row):
	   	$c_name=ucfirst(trim($row->company_name));
	   endforeach;
	   $data['c_name']=$c_name;
		if(!empty($id))
		{			
			$result= $this->b->get_details(array('brand_id'=>$id));
			$data['result']=$result;			
		}
		$data['item_id']=$id;
		$this -> load -> view('dashboard/companies/addProduct', $data);		
	}
public function add_prod($id="")
	{
		if($id=="")
		{
		 	$this->b->add();
			redirect('openComany/'.$this ->session -> userdata('companyID'));
		}
		else
		{
		 	$this->b->update($id);  
			redirect('openComany/'.$this ->session -> userdata('companyID'));
		}
			
			
	}
public function delProduct($id)
	{
		 	if($this->b->delete($id)==true)
			{
				echo $this->delete_success_msg;
			}
			else
			{
				echo $this->delete_er_msg;
			}
	}	
		
}
?>